version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build-frontend:
    executor: node/default
    working_directory: ~/project/frontend/bug-tracker-frontend
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build React App
          command: npm run build
      - store_artifacts:
          path: build
          destination: frontend-build

  build-backend:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/project/backend
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Build Java Backend
          command: mvn clean package
      - store_artifacts:
          path: target
          destination: backend-target

workflows:
  build-and-deploy:
    jobs:
      - build-frontend
      - build-backend
